services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music-sync
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  cache:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
