/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as mainRouteRouteImport } from "./routes/(main)/route";
import { Route as mainIndexRouteImport } from "./routes/(main)/index";
import { Route as AuthSignUpRouteImport } from "./routes/auth/sign-up";
import { Route as AuthSignInRouteImport } from "./routes/auth/sign-in";
import { Route as mainConnectionsIndexRouteImport } from "./routes/(main)/connections/index";
import { Route as mainConnectionsSpotifyIndexRouteImport } from "./routes/(main)/connections/spotify/index";
import { Route as mainConnectionsSpotifyCallbackRouteImport } from "./routes/(main)/connections/spotify/callback";

const mainRouteRoute = mainRouteRouteImport.update({
  id: "/(main)",
  getParentRoute: () => rootRouteImport,
} as any);
const mainIndexRoute = mainIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => mainRouteRoute,
} as any);
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: "/auth/sign-up",
  path: "/auth/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: "/auth/sign-in",
  path: "/auth/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const mainConnectionsIndexRoute = mainConnectionsIndexRouteImport.update({
  id: "/connections/",
  path: "/connections/",
  getParentRoute: () => mainRouteRoute,
} as any);
const mainConnectionsSpotifyIndexRoute =
  mainConnectionsSpotifyIndexRouteImport.update({
    id: "/connections/spotify/",
    path: "/connections/spotify/",
    getParentRoute: () => mainRouteRoute,
  } as any);
const mainConnectionsSpotifyCallbackRoute =
  mainConnectionsSpotifyCallbackRouteImport.update({
    id: "/connections/spotify/callback",
    path: "/connections/spotify/callback",
    getParentRoute: () => mainRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/": typeof mainIndexRoute;
  "/connections/": typeof mainConnectionsIndexRoute;
  "/connections/spotify/callback": typeof mainConnectionsSpotifyCallbackRoute;
  "/connections/spotify/": typeof mainConnectionsSpotifyIndexRoute;
}
export interface FileRoutesByTo {
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/": typeof mainIndexRoute;
  "/connections": typeof mainConnectionsIndexRoute;
  "/connections/spotify/callback": typeof mainConnectionsSpotifyCallbackRoute;
  "/connections/spotify": typeof mainConnectionsSpotifyIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(main)": typeof mainRouteRouteWithChildren;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/(main)/": typeof mainIndexRoute;
  "/(main)/connections/": typeof mainConnectionsIndexRoute;
  "/(main)/connections/spotify/callback": typeof mainConnectionsSpotifyCallbackRoute;
  "/(main)/connections/spotify/": typeof mainConnectionsSpotifyIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/"
    | "/connections/"
    | "/connections/spotify/callback"
    | "/connections/spotify/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/"
    | "/connections"
    | "/connections/spotify/callback"
    | "/connections/spotify";
  id:
    | "__root__"
    | "/(main)"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/(main)/"
    | "/(main)/connections/"
    | "/(main)/connections/spotify/callback"
    | "/(main)/connections/spotify/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren;
  AuthSignInRoute: typeof AuthSignInRoute;
  AuthSignUpRoute: typeof AuthSignUpRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(main)": {
      id: "/(main)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof mainRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(main)/": {
      id: "/(main)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof mainIndexRouteImport;
      parentRoute: typeof mainRouteRoute;
    };
    "/auth/sign-up": {
      id: "/auth/sign-up";
      path: "/auth/sign-up";
      fullPath: "/auth/sign-up";
      preLoaderRoute: typeof AuthSignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/sign-in": {
      id: "/auth/sign-in";
      path: "/auth/sign-in";
      fullPath: "/auth/sign-in";
      preLoaderRoute: typeof AuthSignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(main)/connections/": {
      id: "/(main)/connections/";
      path: "/connections";
      fullPath: "/connections/";
      preLoaderRoute: typeof mainConnectionsIndexRouteImport;
      parentRoute: typeof mainRouteRoute;
    };
    "/(main)/connections/spotify/": {
      id: "/(main)/connections/spotify/";
      path: "/connections/spotify";
      fullPath: "/connections/spotify/";
      preLoaderRoute: typeof mainConnectionsSpotifyIndexRouteImport;
      parentRoute: typeof mainRouteRoute;
    };
    "/(main)/connections/spotify/callback": {
      id: "/(main)/connections/spotify/callback";
      path: "/connections/spotify/callback";
      fullPath: "/connections/spotify/callback";
      preLoaderRoute: typeof mainConnectionsSpotifyCallbackRouteImport;
      parentRoute: typeof mainRouteRoute;
    };
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute;
  mainConnectionsIndexRoute: typeof mainConnectionsIndexRoute;
  mainConnectionsSpotifyCallbackRoute: typeof mainConnectionsSpotifyCallbackRoute;
  mainConnectionsSpotifyIndexRoute: typeof mainConnectionsSpotifyIndexRoute;
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainConnectionsIndexRoute: mainConnectionsIndexRoute,
  mainConnectionsSpotifyCallbackRoute: mainConnectionsSpotifyCallbackRoute,
  mainConnectionsSpotifyIndexRoute: mainConnectionsSpotifyIndexRoute,
};

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
