/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as mainConnectionsIndexRouteImport } from './routes/(main)/connections/index'
import { Route as mainConnectionsSpotifyLikedRouteImport } from './routes/(main)/connections/spotify/liked'
import { Route as mainConnectionsSpotifyCallbackRouteImport } from './routes/(main)/connections/spotify/callback'
import { Route as mainConnectionsSpotifyPlaylistsIndexRouteImport } from './routes/(main)/connections/spotify/playlists/index'
import { Route as mainConnectionsSpotifyPlaylistsPlaylistIdRouteImport } from './routes/(main)/connections/spotify/playlists/$playlistId'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const mainConnectionsIndexRoute = mainConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainConnectionsSpotifyLikedRoute =
  mainConnectionsSpotifyLikedRouteImport.update({
    id: '/connections/spotify/liked',
    path: '/connections/spotify/liked',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainConnectionsSpotifyCallbackRoute =
  mainConnectionsSpotifyCallbackRouteImport.update({
    id: '/connections/spotify/callback',
    path: '/connections/spotify/callback',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainConnectionsSpotifyPlaylistsIndexRoute =
  mainConnectionsSpotifyPlaylistsIndexRouteImport.update({
    id: '/connections/spotify/playlists/',
    path: '/connections/spotify/playlists/',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainConnectionsSpotifyPlaylistsPlaylistIdRoute =
  mainConnectionsSpotifyPlaylistsPlaylistIdRouteImport.update({
    id: '/connections/spotify/playlists/$playlistId',
    path: '/connections/spotify/playlists/$playlistId',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof mainIndexRoute
  '/connections/': typeof mainConnectionsIndexRoute
  '/connections/spotify/callback': typeof mainConnectionsSpotifyCallbackRoute
  '/connections/spotify/liked': typeof mainConnectionsSpotifyLikedRoute
  '/connections/spotify/playlists/$playlistId': typeof mainConnectionsSpotifyPlaylistsPlaylistIdRoute
  '/connections/spotify/playlists/': typeof mainConnectionsSpotifyPlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof mainIndexRoute
  '/connections': typeof mainConnectionsIndexRoute
  '/connections/spotify/callback': typeof mainConnectionsSpotifyCallbackRoute
  '/connections/spotify/liked': typeof mainConnectionsSpotifyLikedRoute
  '/connections/spotify/playlists/$playlistId': typeof mainConnectionsSpotifyPlaylistsPlaylistIdRoute
  '/connections/spotify/playlists': typeof mainConnectionsSpotifyPlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/connections/': typeof mainConnectionsIndexRoute
  '/(main)/connections/spotify/callback': typeof mainConnectionsSpotifyCallbackRoute
  '/(main)/connections/spotify/liked': typeof mainConnectionsSpotifyLikedRoute
  '/(main)/connections/spotify/playlists/$playlistId': typeof mainConnectionsSpotifyPlaylistsPlaylistIdRoute
  '/(main)/connections/spotify/playlists/': typeof mainConnectionsSpotifyPlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/connections/'
    | '/connections/spotify/callback'
    | '/connections/spotify/liked'
    | '/connections/spotify/playlists/$playlistId'
    | '/connections/spotify/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/connections'
    | '/connections/spotify/callback'
    | '/connections/spotify/liked'
    | '/connections/spotify/playlists/$playlistId'
    | '/connections/spotify/playlists'
  id:
    | '__root__'
    | '/(main)'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/(main)/'
    | '/(main)/connections/'
    | '/(main)/connections/spotify/callback'
    | '/(main)/connections/spotify/liked'
    | '/(main)/connections/spotify/playlists/$playlistId'
    | '/(main)/connections/spotify/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/connections/': {
      id: '/(main)/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof mainConnectionsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/connections/spotify/liked': {
      id: '/(main)/connections/spotify/liked'
      path: '/connections/spotify/liked'
      fullPath: '/connections/spotify/liked'
      preLoaderRoute: typeof mainConnectionsSpotifyLikedRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/connections/spotify/callback': {
      id: '/(main)/connections/spotify/callback'
      path: '/connections/spotify/callback'
      fullPath: '/connections/spotify/callback'
      preLoaderRoute: typeof mainConnectionsSpotifyCallbackRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/connections/spotify/playlists/': {
      id: '/(main)/connections/spotify/playlists/'
      path: '/connections/spotify/playlists'
      fullPath: '/connections/spotify/playlists/'
      preLoaderRoute: typeof mainConnectionsSpotifyPlaylistsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/connections/spotify/playlists/$playlistId': {
      id: '/(main)/connections/spotify/playlists/$playlistId'
      path: '/connections/spotify/playlists/$playlistId'
      fullPath: '/connections/spotify/playlists/$playlistId'
      preLoaderRoute: typeof mainConnectionsSpotifyPlaylistsPlaylistIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainConnectionsIndexRoute: typeof mainConnectionsIndexRoute
  mainConnectionsSpotifyCallbackRoute: typeof mainConnectionsSpotifyCallbackRoute
  mainConnectionsSpotifyLikedRoute: typeof mainConnectionsSpotifyLikedRoute
  mainConnectionsSpotifyPlaylistsPlaylistIdRoute: typeof mainConnectionsSpotifyPlaylistsPlaylistIdRoute
  mainConnectionsSpotifyPlaylistsIndexRoute: typeof mainConnectionsSpotifyPlaylistsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainConnectionsIndexRoute: mainConnectionsIndexRoute,
  mainConnectionsSpotifyCallbackRoute: mainConnectionsSpotifyCallbackRoute,
  mainConnectionsSpotifyLikedRoute: mainConnectionsSpotifyLikedRoute,
  mainConnectionsSpotifyPlaylistsPlaylistIdRoute:
    mainConnectionsSpotifyPlaylistsPlaylistIdRoute,
  mainConnectionsSpotifyPlaylistsIndexRoute:
    mainConnectionsSpotifyPlaylistsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
